### ISSUE TITLE
Dependency Issue - fibers

### ISSUE THREAD

**Issue by achatt89** [ziolko/wdio#12]
Hi..
For node v10.x (which is going to be the latest LTS soon), fibers@2.0.2 is deprecated it seems and the recommended version is fibers@3.x

Can you please update the dependency to the latest version of fibers?

Here's the issue raised against fibers package which mentions the need of upgrading fibers to the latest version..

https://github.com/laverdet/node-fibers/issues/390

Regards..

**Comment by ziolko** [comment]
I will take a look at this during weekend. Thanks for your request.

**Comment by ziolko** [comment]
I've released a new version (3.0.0) with using fibers 3. 

Let me know if it solved your issue.
