### ISSUE TITLE
project got obsolete

### ISSUE THREAD

**Issue by christian-bromann** [ziolko/wdio#2]
With WebdriverIO `v4.0.9` we fixed the bug of not being able to use the node debugger. For more information see: http://webdriver.io/guide/testrunner/debugging.html

**Comment by ziolko** [comment]
Hi @christian-bromann,

Awesome! I will test it tomorrow and if it works as expected I will add a notice that this project is obsolete.

I can also transfer ownership of wdio package on npm to https://www.npmjs.com/~christian-bromann. Are you interested?

Have a nice day,
Mateusz

**Comment by christian-bromann** [comment]
nah, I don't need it. Thanks though

**Comment by ziolko** [comment]
Hi Christian,

Sorry for the late response. I've checked the page you've mentioned. I have some concerns about usability. Please take a look at this video: https://www.youtube.com/watch?v=T3Oq4lpCGTs. Can I configure IntelliJ so that I will be able to debug a single test as easily as on the video?

**Comment by christian-bromann** [comment]
> Can I configure IntelliJ so that I will be able to debug a single test as easily as on the video?

Yes you can. You need to set the debugger port to a custom port and you are good to go. There is even a [service](https://www.npmjs.com/package/wdio-debug-service) that does that for you.

**Comment by christian-bromann** [comment]
I strongly recommend to switch back to the original WebdriverIO package. You miss a lot of advantages of the wdio testrunner here like `$` functions and stuff like:

```js
        var results = $$('.commands.property a').filter(function (link) {
            return link.isVisible();
        });
```
