### ISSUE TITLE
Possible to wrap once for all test specs and using wdio.conf.js ?

### ISSUE THREAD

**Issue by vikyd** [ziolko/wdio#4]
This wrapper is good!

World will be very nice if anyone provide some code for :
- wrap once for all test specs
- using wdio.conf.js

**Comment by marek5050** [comment]
```
        var wdio = require('wdio');

        const old_it = it;
        it = function(title, fn){
            return old_it(title,wdio.wrap(fn))
        };
```
I was able to wrap all of the calls to  "it" using the lines above.

**Comment by ziolko** [comment]
Hi @Viky-zhang,

Did @marek5050 answer your first question? 

What do you mean by "using wdio.conf.js"? An example would be perfect :)
