### ISSUE TITLE
Recording test suite as a video

### ISSUE THREAD

**Issue by gergelyke** [ziolko/wdio#8]
Hi!

Is there an easy way to make wdio open up the browser, so I can actually see what's going on? Also, if it could record the video, that would be amazing.

**Comment by ziolko** [comment]
Hi @gergelyke,
You can open the browser in your local computer with `before(wdio.initSelenium);`  (see the [usage](https://github.com/ziolko/wdio#usage) section in README).

Unfortunately I don't know an easy way to record video. Have you found something?

Mateusz
